# Technical Notes {-}
<sup>i</sup> The 2021 ATE survey asked about the racial, ethnic, and gender identities of students in alignment with how the National Center for Education Statistics requests student demographic data from colleges. This involves asking students’ race, ethnicity, and gender in a single question. This approach differs from years prior to 2019, when PIs were asked to report on the race, ethnicity, and gender identities of their students in separate questions. Additionally, ATE PIs were asked to report demographics for only students who had attended at least one course in an academic program that was developed or substantially modified in 2019. Prior to 2019, projects reported demographic information on students who attended at least one course in an ATE-supported academic program. This, in addition to a lower than usual response rate, resulted in a decrease in student demographic data for the 2020 and 2021 reports.

<sup>ii</sup> National data for two-year STEM programs are from the 2017–18 National Center for Education Statistics Digest of Education Statistics Table 321.40 and Table 321.50. (Retrieved from https://nces.ed.gov/programs/digest/current_tables.asp.) Selected fields of study include agriculture and natural resources, biological and biomedical sciences, communications technologies, computer and information sciences, construction, engineering and engineering technologies, mechanic and repair technologies/technicians, physical sciences and science technologies, precision production, and transportation and materials moving. While these are not exact comparison groups, they are as close as available data allow.

<sup>iii</sup> Comparison data for student demographics are from the National Center for Education Statistics. The referenced NCES tables were retrieved from https://nces.ed.gov/programs/digest/current_tables.asp. The national percentage of underrepresented minority students at the two-year level reflects STEM degrees conferred in the 2019-20 school year, derived from Table 321.30. Selected fields of study are the same as those listed in note ii. National rates for certificate programs are not presented because they are not reported by race and STEM field. 
